version: '3'
services:
  postgres:
    image: postgres:16.2
    platform: linux/amd64
    container_name: trail-mates-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./docker/postgres_volume:/var/lib/postgresql/data
  